= Ingress creation
:toc:
:toc-title: ON THIS PAGE
:toclevels: 2

This section shows how to create an ingress. An ingress permanently exposes an application to the outside of the cluster.

== Creating an ingress

An https://kubernetes.io/docs/concepts/services-networking/ingress/[ingress] is a Kubernetes resource that defines a set of routing rules that and is serviced by an ingress controller. 

Before creating an ingress resource, there must be an enabled ingress controller in the cluster. 

There is a wide selection of ingress controllers available. The following link contains a list of the most common ones.

https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/[Ingress Controllers]

=== Deploying an ingress controller
The following link shows how to deploy the `Nginx-ingress` ingress controller. This ingress controller is one of the two ingress controllers supported by the Kubernetes project and works on GCP, AWS, and Azure.

https://kubernetes.github.io/ingress-nginx/deploy/

=== Creating the ingress resource
The ingress resource defines routes between the outside of the cluster to an application running in the cluster.

In the example below, we create an ingress that exposes the `sensor-data-scala-http-ingress-service` service in the namespace `sensor-data-scala`. 

Note here the annotation `kubernetes.io/ingress.class`; this is the selector used by the ingress controller. If you installed another ingress controller, review its documentation to learn how it selects ingress resources.

When applying the following resource to the cluster, the ingress controller creates a route to the service from the outside. 

[source,bash]
----
cat <<EOF | kubectl apply -f - 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sensor-data-http-ingress
  namespace: sensor-data-scala
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
    rules:
    - http:
        paths:
        - path: /sensor-data
          backend:
            servicePort: 3003
            serviceName: sensor-data-scala-http-ingress-service
EOF
----

To check the status of the ingress, view the ingress resource, and see if the ingress controller has assigned an address to it:

[source,bash]
----
> kubectl get ingress -n sensor-data-scala
NAME                       HOSTS   ADDRESS           PORTS     AGE
sensor-data-http-ingress   *       192.168.1.2       80        59s
----

The ingress now has an address, and data can be sent to the ingress on the address `192.168.1.2/sensor-data`