name: Build PRs
on:
  # Trigger the workflow on push only for the master branch
  pull_request:
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Make all  
      run: |
        make all
    
        
